### ISSUE TITLE
previously working integration test failing with Camunda exception

### ISSUE THREAD

**Issue by joel-regen** [camunda-community-hub/camunda-bpm-junit5#15]
so…
trying to run a previously working integration test (a test that spins up spring boot and microservice)  XYZServiceIntegrationTest…
 has no bpm stuff.
 but getting this:
`
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.camunda.bpm.spring.boot.starter.property.CamundaBpmProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1654)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1213)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	... 98 common frames omitted
`

**Comment by joel-regen** [comment]
solved: was using @SpringBootTest annotation. removed it, problem solved.
